export const TRANSACTION_ACTIONS = {
  INITIALIZE_TRANSACTIONS: 'INITIALIZE_TRANSACTIONS',

  ADD_TRANSACTION: 'ADD_TRANSACTION',

  UPDATE_TRANSACTION: 'UPDATE_TRANSACTION',

  DELETE_TRANSACTION: 'DELETE_TRANSACTION',

  CLEAR_TRANSACTIONS: 'CLEAR_TRANSACTIONS',
};